# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 01:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('object', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_country', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1_check', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_state', models.CharField(blank=True, max_length=255, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('address_zip_check', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('cvc_check', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamic_last4', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_month', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_year', models.CharField(blank=True, max_length=255, null=True)),
                ('funding', models.CharField(blank=True, max_length=255, null=True)),
                ('last4', models.CharField(blank=True, max_length=255, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tokenization_method', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriversLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='riders/licenses')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('issuance_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_email', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, upload_to='riders/profile_photos')),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('verified_phone_number', models.BooleanField(default=False)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=244, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='driverslicense',
            name='rider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='rider.Rider'),
        ),
    ]
