# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 01:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_verification_code', models.CharField(blank=True, max_length=255, null=True)),
                ('public_ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('port_number', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_percentage', models.DecimalField(decimal_places=5, max_digits=10, max_length=10)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='vehicles/thumnail_images')),
                ('marketing_image', models.ImageField(blank=True, upload_to='vehicles/thumnail_images')),
                ('max_daily_battery_usage', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
            ],
        ),
    ]
