# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 01:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('rider', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_started', models.DateTimeField()),
                ('date_time_ended', models.DateTimeField()),
                ('seconds_driven', models.DecimalField(decimal_places=10, max_digits=20, max_length=20)),
                ('activation_cost', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('usage_cost', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('path_traveled', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('miles_traveled', models.DecimalField(decimal_places=10, max_digits=20, max_length=20)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rider.Card')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pricing.Pricing')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='rider.Rider')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicle.Vehicle')),
            ],
        ),
    ]
